### ISSUE TITLE
Latest release not compatible with ReClass.NET v1.1

### ISSUE THREAD

**Issue by TETYYS** [KN4CK3R/ReClass.NET-LoadBinaryPlugin#2]
Opening "Attach to Process..." dialog after changing Native helper -> Functions provider to "Load Binary" results in this:
```
System.MissingFieldException: Field not found: 'ReClassNET.Core.EnumerateProcessData.Name'.
   at LoadBinaryPlugin.LoadBinaryPluginExt.EnumerateProcesses(EnumerateProcessCallback callbackProcess)
   at ReClassNET.Core.CoreFunctionsManager.EnumerateProcesses(Action`1 callbackProcess)
   at ReClassNET.Forms.ProcessBrowserForm.RefreshProcessList()
   at ReClassNET.Forms.ProcessBrowserForm..ctor(CoreFunctionsManager coreFunctions, String previousProcess)
   at ReClassNET.Forms.MainForm.attachToProcessToolStripMenuItem_Click(Object sender, EventArgs e)
```

**Comment by KN4CK3R** [comment]
You are right. The plugin needs a current ReClass.NET version. Are you able to compile the current ReClass.NET? If you compile the plugin at this revision https://github.com/ReClassNET/ReClass.NET-LoadBinaryPlugin/commit/dd5ebe027b39d717eb0151f8ed16c3f174d4457c it may work with ReClass.NET 1.1

**Comment by TETYYS** [comment]
It works if compiled on latest masters on both
